# Generated by Django 3.1.2 on 2020-10-12 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('category', models.CharField(max_length=50)),
                ('desc', models.TextField(max_length=5000, null=True)),
                ('course_id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('enroll', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lec_num', models.IntegerField()),
                ('desc', models.TextField(max_length=3500, null=True)),
                ('link', models.URLField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.course')),
            ],
            options={
                'unique_together': {('course', 'lec_num')},
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=1, null=True)),
                ('dob', models.DateField()),
                ('institute', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=10)),
                ('display_pic', models.ImageField(default='', upload_to='')),
                ('is_instructor', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=20)),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.lecture')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.user'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(max_length=3000)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('reported', models.IntegerField(default=0)),
                ('deleted', models.BooleanField(default=False)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.user')),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.lecture')),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('star', models.IntegerField(null=True)),
                ('review', models.TextField(max_length=3500, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.course')),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.user')),
            ],
            options={
                'unique_together': {('course', 'learner')},
            },
        ),
    ]
