# Generated by Django 3.1.2 on 2020-10-16 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0002_course_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='title',
            field=models.CharField(default='Title1', max_length=200),
            preserve_default=False,
        ),
    ]
