# Generated by Django 3.1.2 on 2020-10-16 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0003_lecture_title'),
        ('lms', '0002_auto_20201016_0308'),
    ]

    operations = [
    ]
