# Generated by Django 3.1.2 on 2020-10-16 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0004_merge_20201016_1311'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment',
            new_name='comments',
        ),
        migrations.AddField(
            model_name='course',
            name='name',
            field=models.CharField(default='coursenamedefault', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lecture',
            name='name',
            field=models.CharField(default='lecturenamedefault', max_length=100),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Replies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('replies', models.TextField(max_length=3500)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.comment')),
            ],
        ),
    ]
