# Generated by Django 3.1.2 on 2020-10-17 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0009_chat_chatroom'),
        ('lms', '0009_auto_20201017_1104'),
    ]

    operations = [
    ]
