# Generated by Django 3.1.2 on 2020-10-17 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0010_merge_20201017_1131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatroom',
            name='course',
        ),
        migrations.RemoveField(
            model_name='chatroom',
            name='learner',
        ),
        migrations.DeleteModel(
            name='Chat',
        ),
        migrations.DeleteModel(
            name='Chatroom',
        ),
    ]
